"""Add type field to feed sources

Revision ID: 9103b4db1955
Revises: 5c158407e4ae
Create Date: 2026-01-28 12:16:03.707831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9103b4db1955'
down_revision: Union[str, None] = '5c158407e4ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('feed_sources', sa.Column('type', sa.String(length=20), nullable=True))

    # Set default values for existing rows
    # ArXiv feeds are papers, others are articles
    op.execute("""
        UPDATE feed_sources
        SET type = CASE
            WHEN name LIKE 'ArXiv%' THEN 'paper'
            ELSE 'article'
        END
    """)

    # Now make the column NOT NULL
    op.alter_column('feed_sources', 'type', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feed_sources', 'type')
    # ### end Alembic commands ###
