"""Make access_tokens.refresh_token nullable for client credentials

Revision ID: ffb35ffdc790
Revises: 9103b4db1955
Create Date: 2026-01-28 15:31:36.537076

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ffb35ffdc790"
down_revision: str | None = "9103b4db1955"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "access_tokens",
        "refresh_token",
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "access_tokens",
        "refresh_token",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )
    # ### end Alembic commands ###
